import * as THREE from 'three';
import * as CANNON from 'cannon-es';
import {V,TOP,smooth,seeded} from './world-v5.js';
const clamp=THREE.MathUtils.clamp;
// Cut actual sculpture triangles and close the exposed surfaces.
function cut(tris,n,c){const halves=[[],[]],cuts=[];const mix=(a,b,t)=>({p:a.p.clone().lerp(b.p,t),n:a.n.clone().lerp(b.n,t).normalize(),uv:a.uv.clone().lerp(b.uv,t)});
 for(const tri of tris){const ds=tri.v.map(a=>n.dot(a.p)-c);for(let s=0;s<2;s++){const poly=[],sign=s===0?1:-1;for(let i=0;i<3;i++){const a=tri.v[i],b=tri.v[(i+1)%3],da=ds[i]*sign,db=ds[(i+1)%3]*sign;if(da>=-1e-6)poly.push(a);if((da>1e-6&&db< -1e-6)||(da< -1e-6&&db>1e-6)){const p=mix(a,b,da/(da-db));poly.push(p);if(!s)cuts.push(p.p)}}for(let k=1;k+1<poly.length;k++)halves[s].push({v:[poly[0],poly[k],poly[k+1]],inside:tri.inside})}}
 if(cuts.length>2){const u=V().crossVectors(n,Math.abs(n.y)<.9?V(0,1,0):V(1,0,0)).normalize(),w=V().crossVectors(n,u),seen=new Map();for(const p of cuts)seen.set([p.x,p.y,p.z].map(x=>x.toFixed(5)).join(','),p);const pts=[...seen.values()].map(p=>({p,x:p.dot(u),y:p.dot(w)})).sort((a,b)=>a.x-b.x||a.y-b.y),cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x),hull=[];for(const p of pts){while(hull.length>=2&&cross(hull.at(-2),hull.at(-1),p)<=0)hull.pop();hull.push(p)}const lower=hull.length;for(let i=pts.length-2;i>=0;i--){const p=pts[i];while(hull.length>lower&&cross(hull.at(-2),hull.at(-1),p)<=0)hull.pop();hull.push(p)}hull.pop();for(let s=0;s<2;s++)for(let i=1;i+1<hull.length;i++){const list=s===0?[hull[0],hull[i+1],hull[i]]:[hull[0],hull[i],hull[i+1]],normal=n.clone().multiplyScalar(s===0?-1:1);halves[s].push({inside:true,v:list.map(a=>({p:a.p,n:normal,uv:new THREE.Vector2(a.x,a.y)}))})}}return halves;}
function fracture(shape,type){shape.updateWorldMatrix(true,true);const inverse=shape.parent.matrixWorld.clone().invert();let tris=[];shape.traverse(m=>{if(!m.isMesh)return;const g=m.geometry.index?m.geometry.toNonIndexed():m.geometry.clone(),p=g.attributes.position,n=g.attributes.normal,u=g.attributes.uv,M=inverse.clone().multiply(m.matrixWorld),N=new THREE.Matrix3().getNormalMatrix(M);for(let i=0;i<p.count;i+=3){const verts=[];for(let j=0;j<3;j++)verts.push({p:V().fromBufferAttribute(p,i+j).applyMatrix4(M),n:V().fromBufferAttribute(n,i+j).applyMatrix3(N).normalize(),uv:u?new THREE.Vector2().fromBufferAttribute(u,i+j):new THREE.Vector2()});tris.push({v:verts,inside:false})}g.dispose()});let chunks=[tris];for(let l=0;l<(type==='p'?3:4);l++){const next=[];for(let i=0;i<chunks.length;i++){const part=chunks[i],b=new THREE.Box3();part.forEach(t=>t.v.forEach(a=>b.expandByPoint(a.p)));const center=b.getCenter(V()),n=[V(.15,1,.12),V(1,.16,.42),V(-.27,.17,1),V(.7,1,-.3)][l].normalize();for(const h of cut(part,n,n.dot(center)+(i%2?.005:-.005)))if(h.length>6)next.push(h)}chunks=next}return chunks.map(part=>{const b=new THREE.Box3();part.forEach(t=>t.v.forEach(a=>b.expandByPoint(a.p)));const center=b.getCenter(V()),size=b.getSize(V()),pos=[],nor=[],uv=[],out=part.filter(t=>!t.inside),inside=part.filter(t=>t.inside);for(const t of [...out,...inside])for(const a of t.v){pos.push(a.p.x-center.x,a.p.y-center.y,a.p.z-center.z);nor.push(a.n.x,a.n.y,a.n.z);uv.push(a.uv.x,a.uv.y)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(nor,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.addGroup(0,out.length*3,0);g.addGroup(out.length*3,inside.length*3,1);g.computeBoundingSphere();return {geometry:g,center,size}})}
const STYLES={p:{title:'The first vow',duration:5.8,force:1.8,quote:'One square changes a life.'},n:{title:'The winter rider',duration:7.0,force:2.1,quote:'He arrives before the warning.'},b:{title:'The silent confession',duration:6.2,force:1.6,quote:'Some confessions are never spoken.'},r:{title:'The last gate',duration:6.4,force:3.2,quote:'Nothing crosses the gate twice.'},q:{title:'The quiet command',duration:6.6,force:2.5,quote:'The room goes quiet.'},k:{title:'The weight of a crown',duration:6.0,force:2.0,quote:'For once, the crown pays its own debt.'}};
export class CaptureDirector{
 constructor(world,foley){this.world=world;this.foley=foley;this.cache=new Map();this.debris=[];this.active=null;this.focus=7;this.hidden=[];this.physics=null;this.minClearance=Infinity;}
 prepare(p){const k=p.side+p.type;if(!this.cache.has(k))this.cache.set(k,fracture(p.group.children[0],p.type));return this.cache.get(k)}
 clear(){for(const d of this.debris){this.world.scene.remove(d.mesh);d.mesh.material.forEach(m=>m.dispose())}this.debris=[];if(this.dust){this.world.scene.remove(this.dust);this.dust.geometry.dispose();this.dust.material.dispose();this.dust=null}for(const p of this.hidden)p.group.visible=p.alive;this.hidden=[];this.physics=null;}
 start(p,victim,end,pieces,onDone){this.clear();this.prepare(victim);const style=STYLES[p.type],from=p.group.position.clone(),pos=victim.group.position.clone(),dir=pos.clone().sub(from).setY(0).normalize();if(!dir.lengthSq())dir.z=-1;const side=V(-dir.z,0,dir.x);if(side.x<0)side.negate();const gap=p.radius+victim.radius+.025,contact=pos.clone().addScaledVector(dir,-gap);contact.y=TOP;this.active={p,victim,end,pieces,onDone,style,from,pos,dir,side,contact,gap,base:p.group.quaternion.clone(),hit:false,shot:'anticipation',t:0};this.minClearance=Infinity;this.foley.play('tension',p.type);}
 shatter(){const a=this.active,{p,victim,pos,dir,style}=a;victim.group.visible=false;
 const physics=this.physics=new CANNON.World({gravity:new CANNON.Vec3(0,-8.8,0),allowSleep:true}),stone=new CANNON.Material('stone');physics.addContactMaterial(new CANNON.ContactMaterial(stone,stone,{friction:.72,restitution:.12}));
 const ground=new CANNON.Body({mass:0,material:stone,shape:new CANNON.Plane()});ground.quaternion.setFromEuler(-Math.PI/2,0,0);ground.position.y=TOP;ground.collisionFilterGroup=1;ground.collisionFilterMask=2;physics.addBody(ground);
 const collider=(piece,kinematic=false)=>{const shape=new CANNON.Cylinder(piece.radius*.97,piece.radius*.97,piece.height,12),b=new CANNON.Body({mass:0,type:kinematic?CANNON.Body.KINEMATIC:CANNON.Body.STATIC,material:stone});b.addShape(shape);b.position.set(piece.group.position.x,piece.group.position.y+piece.height/2,piece.group.position.z);b.collisionFilterGroup=1;b.collisionFilterMask=2;physics.addBody(b);return b};
 this.actorBody=collider(p,true);for(const other of a.pieces)if(other!==p&&other!==victim&&other.alive)collider(other);
 const rnd=seeded(942+victim.id.charCodeAt(0)*13),rot=victim.group.quaternion.clone();this.prepare(victim).forEach((f,i)=>{const outer=victim.material.clone(),inner=new THREE.MeshStandardMaterial({color:victim.side==='w'?0xb7aa92:0x454841,roughness:.94});outer.transparent=inner.transparent=true;const m=new THREE.Mesh(f.geometry,[outer,inner]),center=f.center.clone().applyQuaternion(rot);m.position.copy(pos).add(center);m.quaternion.copy(rot);m.castShadow=true;m.receiveShadow=true;this.world.scene.add(m);const s=f.size.clone().multiplyScalar(.42),body=new CANNON.Body({mass:Math.max(.05,s.x*s.y*s.z*8),material:stone,shape:new CANNON.Box(new CANNON.Vec3(Math.max(.015,s.x),Math.max(.015,s.y),Math.max(.015,s.z))),linearDamping:.35,angularDamping:.3});body.position.copy(m.position);body.quaternion.copy(m.quaternion);body.collisionFilterGroup=2;body.collisionFilterMask=1|2;const radial=V(center.x,0,center.z).normalize();body.velocity.set(dir.x*style.force+radial.x*1.35,.7+rnd()*.9,dir.z*style.force+radial.z*1.35);body.angularVelocity.set((rnd()-.5)*7,(rnd()-.5)*5,(rnd()-.5)*7);physics.addBody(body);this.debris.push({mesh:m,body})});
 const count=72,positions=new Float32Array(count*3);this.dustVel=[];for(let i=0;i<count;i++){const angle=rnd()*Math.PI*2;positions.set([pos.x+(rnd()-.5)*.25,TOP+rnd()*victim.height,pos.z+(rnd()-.5)*.25],i*3);this.dustVel.push(V(Math.cos(angle)*1.6+dir.x,.3+rnd()*.8,Math.sin(angle)*1.6+dir.z))}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(positions,3));this.dust=new THREE.Points(g,new THREE.PointsMaterial({color:victim.side==='w'?0xbdaf98:0x777b6e,size:.027,transparent:true,opacity:.45,depthWrite:false}));this.world.scene.add(this.dust);this.foley.play('impact',p.type);if(navigator.vibrate)navigator.vibrate([16,28,9]);}
 update(t,dt=0){const a=this.active;if(!a)return;a.t=t;const {p,victim,from,pos,contact,dir,side,style,end}=a,hit=.60,knight=p.type==='n',high=Math.max(...a.pieces.filter(x=>x.alive).map(x=>x.height))+TOP+.30;p.group.quaternion.copy(a.base);
 if(t<hit){if(t<.18){const e=Math.sin(t/.18*Math.PI);p.group.position.copy(from).addScaledVector(dir,-e*.09)}else if(knight){if(t<.31){p.group.position.copy(from);p.group.position.y=THREE.MathUtils.lerp(TOP,high,smooth((t-.18)/.13))}else if(t<.52){const q=smooth((t-.31)/.21);p.group.position.lerpVectors(from,pos,q);p.group.position.y=high+Math.sin(q*Math.PI)*.24}else{p.group.position.copy(pos);p.group.position.y=THREE.MathUtils.lerp(high,TOP+victim.height+.018,smooth((t-.52)/.08))}}else{const q=clamp((t-.18)/.42,0,1),e=p.type==='r'?q*q*q:smooth(q);p.group.position.lerpVectors(from,contact,e);if(p.type==='b')p.group.position.addScaledVector(side,Math.sin(e*Math.PI)*.12);}
 const horizontal=Math.hypot(p.group.position.x-pos.x,p.group.position.z-pos.z)-p.radius-victim.radius,vertical=p.group.position.y-(pos.y+victim.height);this.minClearance=Math.min(this.minClearance,Math.max(horizontal,vertical));
 }else{if(!a.hit){a.hit=true;this.shatter()}if(knight){p.group.position.copy(pos);p.group.position.y=THREE.MathUtils.lerp(TOP+victim.height+.018,TOP,smooth((t-hit-.055)/.19));}else{p.group.position.lerpVectors(contact,end,smooth((t-.72)/.15));}victim.group.visible=false;}
 if(this.physics&&dt){const slow=t<hit+.075?.22:t<hit+.13?.5:1;this.actorBody.position.set(p.group.position.x,p.group.position.y+p.height*.5,p.group.position.z);this.physics.step(1/120,Math.min(.06,dt)*slow,8);for(const d of this.debris){d.mesh.position.copy(d.body.position);d.mesh.quaternion.copy(d.body.quaternion);const alpha=1-smooth((t-.84)/.1);d.mesh.material.forEach(m=>m.opacity=alpha)}if(this.dust){const data=this.dust.geometry.attributes.position;for(let i=0;i<data.count;i++){const vel=this.dustVel[i];vel.y-=dt*.2;data.setXYZ(i,data.getX(i)+vel.x*dt*slow,Math.max(TOP+.02,data.getY(i)+vel.y*dt*slow),data.getZ(i)+vel.z*dt*slow)}data.needsUpdate=true;this.dust.material.opacity=.45*(1-smooth((t-.71)/.18));}}
 let focus,cam,fov=36;const portrait=clamp(.80/this.world.camera.aspect,1,1.65);
 if(t<.18){a.shot='anticipation';focus=p.group.position.clone().add(V(0,p.height*.52,0));cam=focus.clone().addScaledVector(side,2.5*portrait).addScaledVector(dir,-2.5*portrait).add(V(0,1.4,0));cam.addScaledVector(dir,t*.8);fov=33}
 else if(t<.55){a.shot=knight?'vault':'approach';focus=p.group.position.clone().lerp(pos,.2).add(V(0,p.height*.45,0));cam=focus.clone().addScaledVector(side,4.3*portrait).addScaledVector(dir,-1.2*portrait).add(V(0,1.65*portrait,0));fov=40}
 else if(t<.76){a.shot='impact';focus=pos.clone().add(V(0,knight?victim.height*.85:victim.height*.48,0));cam=focus.clone().addScaledVector(side,4.6*portrait).addScaledVector(dir,-1.6*portrait).add(V(0,1.6,0));fov=37;const age=t-hit;if(age>0&&age<.035){const shake=Math.sin(age*1200)*(.035-age)*1.1;cam.add(V(shake,shake*.5,0))}}
 else if(t<.95){a.shot='aftermath';focus=end.clone().add(V(0,p.height*.5,0));cam=focus.clone().addScaledVector(side,(3.8+smooth((t-.76)/.19)*.3)*portrait).addScaledVector(dir,-2.3*portrait).add(V(0,1.3,0));fov=36}
 else{a.shot='return';this.world.lock();this.focus=this.world.camera.position.distanceTo(this.world.target);return;}
 this.world.camera.position.copy(cam);this.world.camera.fov=fov;this.world.camera.lookAt(focus);this.world.camera.updateProjectionMatrix();this.focus=cam.distanceTo(focus);
 for(const other of this.hidden)other.group.visible=other.alive;this.hidden=[];const segment=focus.clone().sub(cam),len=segment.length();segment.normalize();for(const other of a.pieces){if(!other.alive||other===p||other===victim)continue;const center=other.group.position.clone().add(V(0,other.height*.5,0)),delta=center.clone().sub(cam),along=delta.dot(segment);if(along>0&&along<len-.7&&delta.addScaledVector(segment,-along).length()<other.radius+.25){other.group.visible=false;this.hidden.push(other)}}
 }
 finish(){const a=this.active;if(!a)return;this.clear();a.p.group.position.copy(a.end);a.p.group.quaternion.copy(a.base);a.victim.group.visible=false;this.active=null;this.world.lock();a.onDone();}
 get duration(){return this.active?.style.duration||6}
}
export class Foley{
 constructor(){this.enabled=false;this.context=null}
 play(event,type='p'){if(!this.enabled)return;try{const c=this.context??=new(window.AudioContext||window.webkitAudioContext)();c.resume();const now=c.currentTime,weight={p:1,n:1.2,b:.8,r:1.9,q:1.4,k:1.5}[type]||1,master=c.createGain();master.gain.value=.3;master.connect(c.destination);const tone=(f,gain,duration,delay=0)=>{const o=c.createOscillator(),g=c.createGain();o.frequency.setValueAtTime(f,now+delay);o.frequency.exponentialRampToValueAtTime(Math.max(24,f*.6),now+delay+duration);g.gain.setValueAtTime(.0001,now+delay);g.gain.linearRampToValueAtTime(gain,now+delay+.006);g.gain.exponentialRampToValueAtTime(.0001,now+delay+duration);o.connect(g);g.connect(master);o.start(now+delay);o.stop(now+delay+duration+.03)};const noise=(duration,f,gain,delay=0)=>{const b=c.createBuffer(1,Math.ceil(duration*c.sampleRate),c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,2.8);const s=c.createBufferSource(),filter=c.createBiquadFilter(),g=c.createGain();s.buffer=b;filter.type='bandpass';filter.frequency.value=f;filter.Q.value=.7;g.gain.value=gain;s.connect(filter);filter.connect(g);g.connect(master);s.start(now+delay)};
 if(event==='tension'){noise(.6,650,.08);tone(58/weight,.05,.8)}else if(event==='move'){tone(190,.085,.16);noise(.06,2400,.11)}else{tone(85/weight,.44,.7);tone(166/weight,.22,.35);tone(427/weight,.08,.28);noise(.1,1900,.5);noise(.6,4600,.23,.035);for(let i=0;i<8;i++)noise(.045,2100+i*230,.12/(1+i*.15),.13+i*.065);tone(92/weight,.055,1.3,.11)}setTimeout(()=>master.disconnect(),2400)}catch(e){console.warn('Sound unavailable',e)}}
}
