import {Chess} from './vendor/chess.js';
export const LEVELS=[{name:'Apprentice',skill:0,ms:110,depth:3,description:'A forgiving opponent. Short calculations and deliberate engine imperfections.'},{name:'Soldier',skill:4,ms:250,depth:7,description:'A measured opponent. Spots basic tactics and leaves room to learn.'},{name:'Commander',skill:11,ms:650,depth:12,description:'A demanding opponent. Looks further ahead and punishes loose pieces.'},{name:'Sovereign',skill:19,ms:1500,depth:18,description:'The strongest setting here. Longer calculation and very few concessions.'}];
export class Opponent{
 constructor(onState=()=>{}){this.onState=onState;this.worker=null;this.pending=null;this.ready=false;this.id=0;this.initializing=null;this.lastInfo=null;}
 async init(){if(this.ready)return;if(this.initializing)return this.initializing;this.initializing=new Promise((resolve,reject)=>{const worker=this.worker=new Worker(new URL('./vendor/stockfish/stockfish-19-lite-single.js',import.meta.url));const timer=setTimeout(()=>{this.destroy();reject(new Error('The chess engine took too long to load.'))},25000);worker.onerror=e=>{clearTimeout(timer);this.ready=false;this.initializing=null;const error=new Error(e.message||'The chess engine could not start.');this.pending?.reject(error);this.pending=null;reject(error)};worker.onmessage=e=>{for(const line of String(e.data).split('\n')){if(line==='uciok'){this.send('setoption name Hash value 16');this.send('setoption name Threads value 1');this.send('isready')}else if(line==='readyok'&&!this.ready){clearTimeout(timer);this.ready=true;this.onState('ready');resolve()}else this.line(line)}};this.send('uci')});return this.initializing;}
 send(s){this.worker?.postMessage(s)}
 line(line){const p=this.pending;if(!p)return;if(line.startsWith('info ')&&line.includes(' pv ')){const depth=Number(line.match(/\bdepth (\d+)/)?.[1]||0),rank=Number(line.match(/multipv (\d+)/)?.[1]||1),cp=line.match(/score (cp|mate) (-?\d+)/),move=line.match(/\bpv ([a-h][1-8][a-h][1-8][qrbn]?)/)?.[1];if(cp&&move){const score=cp[1]==='mate'?Math.sign(Number(cp[2]))*(100000-Math.abs(Number(cp[2]))):Number(cp[2]);p.lines.set(rank,{move,score,depth});this.lastInfo={depth,score}}}if(line.startsWith('bestmove ')){clearTimeout(p.timer);this.pending=null;const best=line.split(' ')[1];p.resolve({best,candidates:[...p.lines.values()],info:this.lastInfo});}}
 async choose(fen,{level=1,style='balanced',hint=false,moves=null,startFen=null}={}){await this.init();if(this.pending)throw new Error('Engine is already thinking.');const L=hint?{skill:20,ms:700,depth:15}:LEVELS[level];this.send(`setoption name Skill Level value ${L.skill}`);this.send(`setoption name MultiPV value ${style==='balanced'||hint?1:4}`);if(moves&&startFen)this.send(`position fen ${startFen} moves ${moves.join(' ')}`);else this.send('position fen '+fen);
 const result=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.send('stop');setTimeout(()=>{if(this.pending){this.pending=null;reject(new Error('The engine did not answer.'))}},1000)},Math.max(8000,L.ms*4));this.pending={resolve,reject,timer,lines:new Map()};this.send(`go depth ${L.depth} movetime ${L.ms}`)});
 if(hint||style==='balanced'||result.candidates.length<2)return result.best;
 const legal=new Chess(fen),list=result.candidates.sort((a,b)=>b.score-a.score),top=list[0]?.score??0,tolerance=level===3?12:level===2?22:45;
 let winner=result.best,bestBonus=-Infinity;for(const row of list){if(row.score<top-tolerance||Math.abs(row.score)>90000){if(row.move===result.best)winner=row.move;continue}const move=legal.moves({verbose:true}).find(m=>m.from+m.to+(m.promotion||'')===row.move);if(!move)continue;let bonus=0;if(style==='attacking'){bonus+=(move.captured?12:0)+(move.san.includes('+')?14:0);const r=+move.to[1];bonus+=(move.color==='w'?r:9-r)*1.5;}else{bonus+=(move.flags.includes('k')||move.flags.includes('q')?18:0)+(move.captured?4:0)+(move.piece==='p'?2:0);legal.move(move);bonus-=legal.isAttacked(move.to,legal.turn())?12:0;legal.undo()}bonus-=(top-row.score)*.45;if(bonus>bestBonus){bestBonus=bonus;winner=row.move}}return winner;
 }
 cancel(){if(this.pending||(!this.ready&&this.initializing)){this.destroy()}}
 destroy(){if(this.pending){clearTimeout(this.pending.timer);this.pending.reject(new DOMException('Engine request cancelled','AbortError'));this.pending=null;}this.worker?.terminate();this.worker=null;this.ready=false;this.initializing=null;}
}
