import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {Chess} from './vendor/chess.js';
import {createWorld,V,TOP,squarePosition,smooth} from './world-v5.js';
import {CaptureDirector,Foley} from './cinema-v5.js';
import {DamageField,wearMaterial,damageLabel} from './damage-v5.js';
import {Opponent,LEVELS} from './engine-v5.js';
import {LORE} from './lore.js';
const $=id=>document.getElementById(id),stage=$('stage'),app=$('app'),qa=new URLSearchParams(location.search).has('qa');
const TYPE={p:'Pawn',n:'Knight',b:'Bishop',r:'Rook',q:'Queen',k:'King'},FACTION={w:'Aurell',b:'Veyr'},SCALE=1/.057888091,KEY='ashen-crown-v5';
const world=createWorld(stage),foley=new Foley(),director=new CaptureDirector(world,foley),damage=new DamageField(world),engine=new Opponent(()=>{$('engineStatus').textContent='Stockfish 19 lite is ready.'});
const chess=new Chess(),pieceRoot=new THREE.Group();world.scene.add(pieceRoot);
let pieces=[],templates={},losses=[],history=[],moves=[],startFen=chess.fen(),selected=null,legal=[],mode='loading',animation=null,epoch=0,previewing=false,result=null,toastTimer=0,aiTimer=0;
let settings={mode:'ai',side:'w',level:1,style:'balanced',cinema:'all',damage:true,sound:false,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
let pendingLevel=1,ready=false,lastFrame=performance.now();
function toast(text,ms=3400){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,ms)}
function closeDialogs(){document.querySelectorAll('dialog[open]').forEach(d=>d.close())}
function open(id){closeDialogs();$(id).showModal()}
function applySettings(){foley.enabled=settings.sound;$('cinemaSetting').value=settings.cinema;$('damageSetting').checked=settings.damage;$('soundSetting').checked=settings.sound;$('motionSetting').checked=settings.reduced;damage.update(losses,pieces,settings.damage)}
function snapshot(){return pieces.map(p=>({id:p.id,square:p.square,type:p.type,alive:p.alive}))}
function at(s){return pieces.find(p=>p.alive&&p.square===s)}
function shape(p,type){if(p.material)p.material.dispose();p.group.clear();const obj=templates[p.side+type].clone(true);obj.position.set(0,0,0);obj.scale.setScalar(SCALE);obj.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(obj),center=box.getCenter(V()),size=box.getSize(V());obj.position.x-=center.x;obj.position.z-=center.z;obj.position.y-=box.min.y;const material=wearMaterial((p.side==='w'?world.mat.white:world.mat.black).clone(),p.id.charCodeAt(0)*.37+Number(p.id[1]));obj.traverse(m=>{if(m.isMesh){m.material=material;m.castShadow=m.receiveShadow=true}});p.group.add(obj);p.material=material;p.height=size.y;p.radius=Math.max(size.x,size.z)*.5;p.type=type;p.group.traverse(m=>m.userData.piece=p)}
function build(){pieces.forEach(p=>p.material.dispose());pieceRoot.clear();pieces=[];for(const row of chess.board())for(const cell of row){if(!cell)continue;const lore=LORE[cell.square]||[`${FACTION[cell.color]} ${TYPE[cell.type]}`,'One more witness to a broken peace.'];const p={id:cell.square,square:cell.square,side:cell.color,type:cell.type,name:lore[0],story:lore[1],alive:true,group:new THREE.Group()};shape(p,p.type);p.group.rotation.y=Math.PI;p.group.position.copy(squarePosition(p.square));pieceRoot.add(p.group);pieces.push(p)}}
function restore(states){for(const s of states){const p=pieces.find(p=>p.id===s.id);if(!p)continue;if(p.type!==s.type)shape(p,s.type);Object.assign(p,{square:s.square,alive:s.alive});p.group.visible=s.alive;p.group.position.copy(squarePosition(s.square));p.group.rotation.set(0,Math.PI,0);p.group.scale.setScalar(1);p.material.transparent=false;p.material.opacity=1;}damage.update(losses,pieces,settings.damage);clearSelection()}
const overlays=new THREE.Group();world.scene.add(overlays);
function plane(color,alpha,size=.98){const m=new THREE.Mesh(new THREE.PlaneGeometry(size,size),new THREE.MeshBasicMaterial({color,transparent:true,opacity:alpha,depthWrite:false}));m.rotation.x=-Math.PI/2;m.visible=false;overlays.add(m);return m}
const selection=plane(0xcee5a3,.19),lastFrom=plane(0xd0b786,.12),lastTo=plane(0xd0b786,.19),checkMark=plane(0xbe6a53,.22);
const dots=[];for(let i=0;i<32;i++){const m=new THREE.Mesh(new THREE.RingGeometry(.065,.11,28),new THREE.MeshBasicMaterial({color:0xd6dfbc,transparent:true,opacity:.9,depthWrite:false,side:THREE.DoubleSide}));m.rotation.x=-Math.PI/2;m.visible=false;overlays.add(m);dots.push(m)}
function clearSelection(){selected=null;legal=[];selection.visible=false;dots.forEach(d=>d.visible=false);$('selectedInfo').hidden=true}
function choose(p){if(mode!=='play'||!p)return;clearSelection();selected=p;if(p.side===chess.turn()&&(settings.mode==='local'||p.side===settings.side))legal=chess.moves({square:p.square,verbose:true});selection.visible=true;selection.position.copy(squarePosition(p.square,TOP+.014));const choices=[...new Map(legal.map(m=>[m.to,m])).values()];choices.forEach((move,i)=>{if(!dots[i])return;const d=dots[i];d.visible=true;d.position.copy(squarePosition(move.to,TOP+.018));d.scale.setScalar(move.captured?3.7:1);d.material.color.set(move.captured?0xcfaa81:0xd6dfbc)});$('selectedInfo').hidden=false;$('selectedName').textContent=p.name;}
function inspect(p){if(!p)return;$('loreMeta').textContent=`${FACTION[p.side]} · ${TYPE[p.type]} · ${p.alive?p.square.toUpperCase():'Lost'}`;$('loreName').textContent=p.name;$('loreText').textContent=p.story;open('pieceDialog')}
function sync(){const turn=chess.turn(),ai=settings.mode==='ai'&&turn!==settings.side;let text=settings.mode==='ai'?(turn===settings.side?'Your move':'Opponent to move'):(turn==='w'?'White to move':'Black to move');if(mode==='thinking')text='Thinking';if(mode==='hint')text='Finding a hint';if(result)text=result.title;else if(chess.inCheck())text+=' · Check';$('turnText').textContent=text;$('turnDot').classList.toggle('black',turn==='b');$('turnDot').classList.toggle('status-pulse',mode==='thinking'||mode==='hint');$('opponentText').textContent=settings.mode==='ai'?`${LEVELS[settings.level].name} · Move ${Math.floor(moves.length/2)+1}`:`Two players · Move ${Math.floor(moves.length/2)+1}`;
 const busy=!['play','thinking','ended'].includes(mode);$('undoBtn').disabled=history.length===0||busy;$('hintBtn').disabled=mode!=='play'||!!result||(settings.mode==='ai'&&ai);$('previewBtn').disabled=mode!=='play'||!!result;$('resignBtn').disabled=busy||!!result;$('newBtn').disabled=busy;checkMark.visible=false;if(chess.inCheck()){const k=pieces.find(p=>p.alive&&p.type==='k'&&p.side===turn);if(k){checkMark.visible=true;checkMark.position.copy(squarePosition(k.square,TOP+.012))}}if(moves.length){const m=moves.at(-1);lastFrom.visible=lastTo.visible=true;lastFrom.position.copy(squarePosition(m.slice(0,2),TOP+.01));lastTo.position.copy(squarePosition(m.slice(2,4),TOP+.01))}else lastFrom.visible=lastTo.visible=false;
}
function record(){$('whiteDamage').value=damage.state.w;$('blackDamage').value=damage.state.b;for(const [key,side] of [['white','w'],['black','b']])$(key+'DamageText').textContent=`${damageLabel(damage.state[side])} · ${losses.filter(x=>x.side===side).length} pieces lost`;
 $('moveRecord').replaceChildren();const san=chess.history();if(!san.length)$('moveRecord').textContent='No moves yet.';for(let i=0;i<san.length;i+=2){const row=document.createElement('div');for(const text of [`${i/2+1}.`,san[i],san[i+1]||'']){const s=document.createElement('span');s.textContent=text;row.append(s)}$('moveRecord').append(row)}
 $('journalContent').replaceChildren();for(const p of pieces){const article=document.createElement('article');article.className='journal-entry';const meta=document.createElement('small'),name=document.createElement('h4'),story=document.createElement('p');meta.textContent=`${FACTION[p.side]} · ${TYPE[p.type]} · ${p.alive?p.square.toUpperCase():'Captured'}`;name.textContent=p.name;story.textContent=p.story;article.append(meta,name,story);$('journalContent').append(article)}}
function save(){if(qa)return;try{localStorage.setItem(KEY,JSON.stringify({version:5,startFen,moves,settings,result}))}catch(e){console.warn('Autosave unavailable',e)}}
function finalState(move,p,victim){p.square=move.to;p.group.position.copy(squarePosition(move.to));p.group.rotation.set(0,Math.PI,0);if(victim){victim.alive=false;victim.group.visible=false;losses.push({id:victim.id,type:victim.type,side:victim.side,square:move.to,name:victim.name,by:p.name})}if(move.promotion)shape(p,move.promotion);if(move.flags.includes('k')||move.flags.includes('q')){const r=p.side==='w'?'1':'8',king=move.flags.includes('k'),rook=at((king?'h':'a')+r);if(rook){rook.square=(king?'f':'d')+r;rook.group.position.copy(squarePosition(rook.square))}}}
function checkEnd(){if(!chess.isGameOver())return false;let title='Draw',detail='The war ends without a winner.';if(chess.isCheckmate()){const winner=chess.turn()==='w'?'b':'w';title=settings.mode==='ai'?(winner===settings.side?'Victory':'Defeat'):`${FACTION[winner]} wins`;detail=`Checkmate. ${FACTION[winner]} holds the Treaty Table.`;}else if(chess.isStalemate())detail='Stalemate. No legal move remains, and the king is not in check.';else if(chess.isThreefoldRepetition())detail='Draw by threefold repetition.';else if(chess.isInsufficientMaterial())detail='Neither court has enough material to force checkmate.';else if(chess.isDrawByFiftyMoves?.())detail='Draw by the fifty-move rule.';result={title,detail};mode='ended';showResult();return true}
function showResult(){if(!result)return;$('resultTitle').textContent=result.title;$('resultDetail').textContent=result.detail;open('resultDialog')}
function finishMove(move,p,victim){animation=null;finalState(move,p,victim);damage.update(losses,pieces,settings.damage);mode='play';clearSelection();checkEnd();sync();record();save();scheduleAI()}
function uci(move){return move.from+move.to+(move.promotion||'')}
function promotionDialog(){return new Promise(resolve=>{const d=document.createElement('dialog');d.innerHTML='<header><h2>Choose your promotion</h2></header><p class="subtext">The pawn has reached the far court.</p><div class="promotion-options"></div>';for(const t of ['q','r','b','n']){const b=document.createElement('button');b.textContent=TYPE[t];b.onclick=()=>d.close(t);d.querySelector('div').append(b)}d.addEventListener('close',()=>{const t=d.returnValue;d.remove();resolve(t||null)},{once:true});document.body.append(d);d.showModal()})}
async function play(from,to,promotion=null,byAI=false){if(!['play','thinking'].includes(mode)||result)return false;if(!byAI&&mode!=='play')return false;const p=at(from);if(!p||p.side!==chess.turn())return false;if(!byAI&&settings.mode==='ai'&&p.side!==settings.side)return false;const options=chess.moves({square:from,verbose:true}),candidate=options.find(m=>m.to===to);if(!candidate)return false;
 if(candidate.promotion&&!promotion){mode='promotion';sync();promotion=await promotionDialog();mode='play';if(!promotion){sync();return false}}const victim=candidate.flags.includes('e')?at(to[0]+from[1]):at(to);const before={board:snapshot(),losses:structuredClone(losses)};let move;try{move=chess.move({from,to,...(promotion?{promotion}:{})})}catch{return false}history.push(before);moves.push(uci(move));clearSelection();closeDialogs();const cinematic=victim&&!settings.reduced&&(settings.cinema==='all'||(settings.cinema==='key'&&victim.type!=='p'));
 if(cinematic){mode='capture';previewing=false;overlays.visible=false;app.classList.add('cinematic');$('skipBtn').hidden=false;$('caption').classList.remove('visible');$('captureMeta').textContent=`${FACTION[p.side]} · ${TYPE[p.type]} takes ${TYPE[victim.type]}`;$('captureTitle').textContent=p.name;$('captureText').textContent=`${victim.name} falls. ${p.story}`;director.start(p,victim,squarePosition(to),pieces,()=>{app.classList.remove('cinematic');$('skipBtn').hidden=true;$('caption').classList.remove('visible');overlays.visible=true;finishMove(move,p,victim)});animation={kind:'capture',elapsed:0,duration:director.duration};}
 else{mode='moving';const start=p.group.position.clone(),end=squarePosition(to);if(victim)victim.group.visible=false;const knight=p.type==='n';animation={kind:'move',elapsed:0,duration:settings.reduced?.12:knight?.55:.32,update(t){p.group.position.lerpVectors(start,end,smooth(t));if(knight&&!settings.reduced)p.group.position.y+=Math.sin(t*Math.PI)*2.05},done(){foley.play(victim?'impact':'move',p.type);finishMove(move,p,victim)}}}
 sync();return true;
}
function scheduleAI(){clearTimeout(aiTimer);if(mode!=='play'||result||settings.mode!=='ai'||chess.turn()===settings.side)return;const id=epoch;mode='thinking';sync();aiTimer=setTimeout(async()=>{try{const move=await engine.choose(chess.fen(),{level:settings.level,style:settings.style,moves:[...moves],startFen});if(epoch!==id||mode!=='thinking')return;if(!/^[a-h][1-8][a-h][1-8][qrbn]?$/.test(move))throw Error('The engine returned no move.');await play(move.slice(0,2),move.slice(2,4),move[4]||null,true)}catch(e){if(e.name==='AbortError'||epoch!==id)return;mode='play';sync();$('engineStatus').textContent='Engine unavailable. Use Retry opponent below.';toast('The opponent could not respond. Open the menu to retry.',6000);let retry=$('engineRetry');if(!retry){retry=document.createElement('button');retry.id='engineRetry';retry.className='menu-row';retry.textContent='Retry opponent';$('menuDialog').append(retry)}retry.onclick=()=>{engine.destroy();closeDialogs();scheduleAI()};console.warn(e)}},300)}
function cancelEngine(){epoch++;clearTimeout(aiTimer);engine.cancel()}
function undo(){if(!history.length||!['play','thinking','ended'].includes(mode))return;cancelEngine();result=null;let count=1;if(settings.mode==='ai'&&chess.turn()===settings.side&&history.length>=2)count=2;while(count--&&history.length){chess.undo();moves.pop();const previous=history.pop();losses=previous.losses;restore(previous.board)}mode='play';damage.update(losses,pieces,settings.damage);clearSelection();sync();record();save();closeDialogs();scheduleAI();}
async function hint(){if(mode!=='play'||result)return;closeDialogs();clearSelection();const id=epoch;mode='hint';sync();try{const move=await engine.choose(chess.fen(),{hint:true,moves:[...moves],startFen});if(id!==epoch||mode!=='hint')return;mode='play';choose(at(move.slice(0,2)));const c=chess.moves({verbose:true}).find(m=>uci(m)===move);toast(c?`Consider ${c.san}: ${move.slice(0,2).toUpperCase()} → ${move.slice(2,4).toUpperCase()}`:'No hint available.');sync()}catch(e){if(e.name==='AbortError')return;mode='play';sync();toast('The hint engine could not load. Please retry.')}}
function startGame(options=settings,fen=null){cancelEngine();if(director.active){director.active.onDone=()=>{};director.finish()}director.clear();animation=null;closeDialogs();Object.assign(settings,options);result=null;chess.load(fen||new Chess().fen());startFen=chess.fen();history=[];losses=[];moves=[];build();mode='play';applySettings();world.orient(settings.mode==='ai'?settings.side:'w');clearSelection();sync();record();save();scheduleAI()}
function setupNew(){pendingLevel=settings.level;$('modeSetting').value=settings.mode;$('sideSetting').value=settings.side;$('styleSetting').value=settings.style;setLevel(pendingLevel);$('aiOptions').hidden=$('sideRow').hidden=settings.mode==='local';open('newDialog')}
function setLevel(n){pendingLevel=n;document.querySelectorAll('[data-level]').forEach(b=>b.classList.toggle('active',Number(b.dataset.level)===n));$('levelDescription').textContent=LEVELS[n].description}
function replayStored(stored){settings={...settings,...stored.settings};chess.load(stored.startFen);startFen=chess.fen();build();history=[];moves=[];losses=[];for(const text of stored.moves){const p=at(text.slice(0,2));if(!p)throw Error('Invalid saved move');const candidate=chess.moves({square:p.square,verbose:true}).find(m=>uci(m)===text);if(!candidate)throw Error('Invalid saved game');const victim=candidate.flags.includes('e')?at(text[2]+p.square[1]):at(text.slice(2,4));history.push({board:snapshot(),losses:structuredClone(losses)});const m=chess.move({from:text.slice(0,2),to:text.slice(2,4),...(text[4]?{promotion:text[4]}:{})});moves.push(text);finalState(m,p,victim)}result=stored.result||null;mode=result?'ended':'play';}
function preview(type='n'){if(mode!=='play'||result)return;closeDialogs();const p=pieces.find(x=>x.alive&&x.type===type&&x.side===settings.side)||pieces.find(x=>x.alive&&x.type===type),victim=pieces.find(x=>x.alive&&x.side!==p?.side&&x.type==='p');if(!p||!victim){toast('This preview needs an available attacker and opposing pawn.');return}if(settings.reduced){toast('Turn off Reduce motion to preview a capture.');return}const saved=snapshot();previewing=true;mode='capture';clearSelection();p.group.position.copy(squarePosition('d4'));victim.group.position.copy(squarePosition('e6'));const others=pieces.filter(x=>x!==p&&x!==victim&&['d4','e6'].includes(x.square));others.forEach(x=>x.group.visible=false);overlays.visible=false;app.classList.add('cinematic');$('skipBtn').hidden=false;$('captureMeta').textContent=`Capture preview · ${TYPE[p.type]}`;$('captureTitle').textContent=p.name;$('captureText').textContent=`${victim.name} falls. Your match is preserved.`;director.start(p,victim,squarePosition('e6'),pieces,()=>{animation=null;previewing=false;restore(saved);mode='play';overlays.visible=true;app.classList.remove('cinematic');$('skipBtn').hidden=true;$('caption').classList.remove('visible');sync();scheduleAI()});animation={kind:'capture',elapsed:0,duration:director.duration};sync()}
function tick(now){const dt=Math.min(.065,(now-lastFrame)/1000);lastFrame=now;if(animation){const a=animation;a.elapsed+=dt;const t=Math.min(1,a.elapsed/a.duration);if(a.kind==='capture'){director.update(t,dt);$('caption').classList.toggle('visible',t>.775&&t<.95);if(t===1)director.finish()}else{a.update(t);if(t===1)a.done()}}if(mode!=='capture')world.lock();world.render(mode==='capture',director.focus)}
const ray=new THREE.Raycaster(),pickPlane=new THREE.Plane(V(0,1,0),-TOP);let down=null;
function pick(x,y){const r=world.renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((x-r.left)/r.width*2-1,1-(y-r.top)/r.height*2),world.camera);const hits=ray.intersectObject(pieceRoot,true);for(const h of hits){const p=h.object.userData.piece;if(p?.alive&&p.group.visible)return {piece:p,square:p.square}}const pos=ray.ray.intersectPlane(pickPlane,V());if(!pos)return null;const file=Math.floor(pos.x+4),rank=Math.floor(4-pos.z);return file>=0&&file<8&&rank>=0&&rank<8?{square:'abcdefgh'[file]+(rank+1)}:null}
world.renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,id:e.pointerId}});world.renderer.domElement.addEventListener('pointercancel',()=>down=null);world.renderer.domElement.addEventListener('pointerup',e=>{const d=down;down=null;if(!d||d.id!==e.pointerId||Math.hypot(d.x-e.clientX,d.y-e.clientY)>12||mode!=='play')return;const h=pick(e.clientX,e.clientY);if(!h){clearSelection();return}if(selected&&legal.some(m=>m.to===h.square)){play(selected.square,h.square);return}if(h.piece)choose(h.piece);else clearSelection()});
// No orbit, wheel, pinch, or automatic turn-flip handlers: camera moves only in capture scenes.
$('selectedInfo').onclick=()=>inspect(selected);$('menuBtn').onclick=()=>open('menuDialog');$('journalBtn').onclick=$('recordBtn').onclick=$('resultRecordBtn').onclick=()=>{record();open('journalDialog')};document.querySelectorAll('.dismiss').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}));
$('newBtn').onclick=$('playAgainBtn').onclick=setupNew;$('startBtn').onclick=()=>startGame({...settings,mode:$('modeSetting').value,side:$('sideSetting').value,style:$('styleSetting').value,level:pendingLevel});document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>setLevel(Number(b.dataset.level)));$('modeSetting').onchange=()=>$('aiOptions').hidden=$('sideRow').hidden=$('modeSetting').value==='local';$('undoBtn').onclick=undo;$('hintBtn').onclick=hint;$('previewBtn').onclick=()=>preview();$('skipBtn').onclick=()=>{if(director.active)director.finish()};
$('cinemaSetting').onchange=()=>{settings.cinema=$('cinemaSetting').value;save()};$('damageSetting').onchange=()=>{settings.damage=$('damageSetting').checked;damage.update(losses,pieces,settings.damage);save()};$('soundSetting').onchange=()=>{settings.sound=$('soundSetting').checked;foley.enabled=settings.sound;foley.play('move');save()};$('motionSetting').onchange=()=>{settings.reduced=$('motionSetting').checked;save()};$('resignBtn').onclick=()=>open('resignDialog');$('confirmResign').onclick=()=>{cancelEngine();result={title:'Resigned',detail:`${FACTION[settings.mode==='ai'?settings.side:chess.turn()]} lays down the crown.`};mode='ended';sync();save();showResult()};
$('exportBtn').onclick=()=>{const blob=new Blob([chess.pgn()+'\n'],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ashen-crown-match.pgn';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)};
new ResizeObserver(()=>{world.resize(stage.clientWidth,stage.clientHeight);if(mode!=='capture')world.lock()}).observe(stage);world.resize(stage.clientWidth,stage.clientHeight);world.lock();world.renderer.setAnimationLoop(tick);
world.renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelEngine();mode='error';window.gameError(new Error('Graphics context lost. The last completed move was saved.'))});
async function init(){const gltf=await new GLTFLoader().loadAsync('./assets/chess_set.gltf');$('loadingDetail').textContent='Preparing carved stone and polished marble.';for(const side of ['w','b'])for(const [type,name] of Object.entries(TYPE)){const stem=`piece_${name.toLowerCase()}_${side==='w'?'white':'black'}`,source=gltf.scene.getObjectByName(stem)||gltf.scene.children.find(n=>n.name.startsWith(stem+'_'));if(!source)throw Error('Missing sculpture: '+stem);templates[side+type]=source;}await world.install(gltf,SCALE);let stored;try{stored=!qa&&JSON.parse(localStorage.getItem(KEY)||'null')}catch{}if(stored?.version===5){try{replayStored(stored)}catch{chess.reset();history=[];moves=[];losses=[];result=null;build();mode='play'}}else{build();mode='play'}if(qa)settings.mode='local';applySettings();world.orient(settings.mode==='ai'?settings.side:'w');damage.update(losses,pieces,settings.damage);sync();record();await world.renderer.compileAsync(world.scene,world.camera);world.render();$('loading').hidden=true;ready=true;window.__ASHEN_READY__=true;if(settings.mode==='ai')engine.init().catch(e=>{$('engineStatus').textContent='Engine loading failed. Retry available after your move.';console.warn(e)});scheduleAI();}
if(qa)window.__ASHEN_QA__={state:()=>({ready,mode,fen:chess.fen(),pieces:pieces.filter(p=>p.alive).length,board:snapshot(),losses:structuredClone(losses),damage:{...damage.state},settings:{...settings},camera:{position:world.camera.position.toArray(),quaternion:world.camera.quaternion.toArray(),fov:world.camera.fov},minClearance:director.minClearance,shot:director.active?.shot,engineReady:engine.ready,result}),select:s=>choose(at(s)),move:(from,to,promotion)=>play(from,to,promotion),preview,skip:()=>director.finish(),project:s=>{const q=squarePosition(s,TOP+.15).project(world.camera);return {x:(q.x+1)*stage.clientWidth/2,y:(1-q.y)*stage.clientHeight/2}},load:(fen,opts={})=>startGame({...settings,mode:'local',...opts},fen),newAI:(opts={})=>startGame({...settings,mode:'ai',...opts}),hint,undo,
 damageScenario:()=>{cancelEngine();startGame({...settings,mode:'local'},'r3k2r/pp1n1ppp/2p1p3/3pP3/3P4/2N2N2/PPP2PPP/R2QK2R w KQkq - 0 1');losses=[{id:'d8',type:'q',side:'b',square:'d6'},{id:'c8',type:'b',side:'b',square:'f5'},{id:'f8',type:'b',side:'b',square:'b4'},{id:'g8',type:'n',side:'b',square:'g5'},{id:'b1',type:'n',side:'w',square:'c3'},{id:'c1',type:'b',side:'w',square:'e5'},{id:'f1',type:'b',side:'w',square:'b5'}];damage.update(losses,pieces,true);record();sync()},
 setTime:t=>{if(!director.active)return;world.renderer.setAnimationLoop(null);const target=t*director.duration;while(animation.elapsed<target){const dt=Math.min(1/60,target-animation.elapsed);animation.elapsed+=dt;director.update(animation.elapsed/animation.duration,dt)}$('caption').classList.toggle('visible',t>.775&&t<.95);world.render(true,director.focus)},resume:()=>{lastFrame=performance.now();world.renderer.setAnimationLoop(tick)},render:()=>world.render(mode==='capture',director.focus),ray:pick};
init().catch(window.gameError);
