export const LORE={
 a1:['The Last Gate','The western fortress surrendered once, then asked to be carved into a rook so it could never retreat again.'],
 b1:['Sir Cael, The Winter Rider','He crossed the frozen north to warn Aurell that the peace had already failed. He arrived one day too late.'],
 c1:['Ilyr, Keeper of Cinders','He memorised every name spoken before a battle and spent forty years reciting them back to the crown.'],
 d1:['Queen Elowen, The Bright Ruin','She signed the treaty knowing it would fail, because one night without war was still worth buying.'],
 e1:['Aurel IV, The Crown Without Sleep','Every move is made in his name. Every missing piece is counted against him.'],
 f1:['Saint Vessa of the Split Bell','She blessed both armies before discovering they were praying for the same victory.'],
 g1:['Ser Oris, The Thaw Rider','He was born during the first siege and has never seen a winter without soldiers in it.'],
 h1:['The Dawn Bastion','Its stones came from the palace nursery. The royal children learned to walk where soldiers now die.'],
 a2:['Mara of the Reed Gate','She moved one ink mark on a military map and sent an army around her village instead of through it.'],
 b2:['Tomas Bellmaker','He melted the treaty bells into armour when their sound stopped meaning peace.'],
 c2:['Nerin, Son of No Banner','He enlisted under an empty crest so no lord could claim the life he gave.'],
 d2:['Sela of the Salt Road','She carried letters between enemies until the letters became orders to kill each other.'],
 e2:['Ser Orren, The First Vow','He carried the first treaty over the winter pass and still believes words should weigh more than steel.'],
 f2:['Pera the Orchard Keeper','Her orchard became a battlefield. She fights so one tree might outlive the war.'],
 g2:['Milo, The Unrecorded','He scratched his own name from the rolls after learning history only remembers officers.'],
 h2:['Ysra of the River Steps','She ferried refugees at night and soldiers by day, never asking which side deserved the shore.'],
 a8:['The Black Rampart','Built from conquered gatehouses, it carries the keys of seven cities inside its hollow crown.'],
 b8:['Veyr Blackmane','He returned from the eastern battle without his horse and has never spoken of the road home.'],
 c8:['The Veiled Confessor','He hears the dying truth of soldiers and seals each secret beneath black wax.'],
 d8:['Queen Maevra, The Quiet Knife','She never raised her voice in council. Three kingdoms disappeared while she whispered.'],
 e8:['Veyr IX, The Hollow Crown','He inherited a victory no living witness remembers and a war every child understands.'],
 f8:['Mother Sable','She taught battlefield surgeons to pray only after their hands stopped shaking.'],
 g8:['Rooke of the Red Snow','The name is a joke. He is a knight, and the snow was only red once. Once was enough.'],
 h8:['The Night Citadel','Its foundations contain the first stone thrown when the treaty collapsed.'],
 a7:['Ashen Fen','He joined for bread and stayed because going home required crossing the front.'],
 b7:['Kell, Keeper of Crows','He fed the battlefield birds so they would stop feeding on the dead.'],
 c7:['Dara Without Hearth','Her village exists on maps printed before the war and nowhere else.'],
 d7:['Old Ren','He has survived long enough to serve three kings and trust none of them.'],
 e7:['Venn the Lamp-Lighter','He lit the surrender road every night even after both armies forgot it existed.'],
 f7:['Tal of the Broken Oar','A river conscript who cannot swim and somehow keeps surviving crossings.'],
 g7:['Eris, Last of Hollow Farm','She carries soil from home in a pouch under her armour.'],
 h7:['Noam the Witness','His only order was to remember what happened. He wishes they had given him any other task.']
};
